#!/usr/bin/env bash
#
# Deploy Geneva Bengal to production. Run on the server itself (over SSH),
# from the project root — see DEPLOY.md. Alternative to
# .github/workflows/deploy.yml (which rsyncs a CI-built artifact instead of
# building on the server) — more complete (maintenance mode, SSR restart
# attempt), preferred for a watched manual deploy.
#
# Assumes `git`, `composer`, `node`/`npm` and `php` are already on PATH for
# the SSH session (adjust with full paths below if your hosting exposes
# them differently) and that `.env` already exists on the server with
# production values (see DEPLOY.md #1 — never generated by this script).

set -euo pipefail
cd "$(dirname "$0")"

if [ ! -f .env ]; then
    echo "No .env found in $(pwd) — create it from .env.example with production values first (see DEPLOY.md #1)." >&2
    exit 1
fi

echo "==> git pull"
git pull --ff-only origin main

echo "==> composer install (production, no dev dependencies)"
composer install --no-dev --optimize-autoloader --no-interaction

echo "==> npm ci && npm run build (client bundle + SSR bundle)"
npm ci
npm run build

echo "==> maintenance mode: down"
# --retry tells already-connected clients when to poll again; render
# requests during the short migrate window as a 503 rather than a
# half-migrated schema.
php artisan down --retry=15 || true

echo "==> php artisan migrate --force"
php artisan migrate --force

echo "==> php artisan db:seed --force"
# Every seeder in DatabaseSeeder::run() is idempotent (firstOrCreate/upsert
# by a stable key) — safe to re-run on every deploy, not just the first.
# This is what keeps roles/super_admin/colors/CMS pages/site
# settings/homepage gallery rows in sync with the repo without a manual SSH
# step each time a seeder changes or a new one is added.
php artisan db:seed --force

echo "==> storage:link"
# No-op (exit 0) if it already exists from a previous deploy.
php artisan storage:link || true

echo "==> cache config/routes/views"
php artisan config:clear
php artisan config:cache
php artisan route:cache
php artisan view:cache

echo "==> maintenance mode: up"
php artisan up

echo "==> restart the SSR process"
if command -v supervisorctl >/dev/null 2>&1; then
    # Cloud Server (VPS) — see deploy/supervisor/geneva-bengal.conf.
    supervisorctl restart geneva-bengal-ssr geneva-bengal-queue
else
    # Hébergement Web mutualisé: no shell-level process manager available
    # (see DEPLOY.md #2) — the Node.js site has to be restarted from the
    # Infomaniak Manager (or their CLI, if the plan exposes one) instead.
    echo "supervisorctl not found: restart the SSR Node.js site manually from the Infomaniak Manager (see DEPLOY.md #2)."
fi

echo "==> done"
